AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.1.0
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Appraisals'
  Exclude:
    - 'spec/dummy/**/*'
    - 'lib/generators/**/*'

Metrics/LineLength:
  Max: 150

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
